# prometheus 的配置文件
global:
  scrape_interval:     15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  # 将下面这一部分复制到 prometheus配置文件，让prometheus通过 http://localhost:8762/monitor/prometheus 拉取监控数据
  - job_name: 'springboot-project-metrics'
    metrics_path: '/monitor/prometheus'
    static_configs:
     - targets: ['部署face-server的机器ip:8762']
